// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type AppRouteHandlerRoutes = "/api/currency-rates" | "/api/test-curl" | "/blog/feed.xml"
type PageRoutes = never
type LayoutRoutes = "/" | "/checkout" | "/email-login" | "/forgot-password" | "/guides/disable-2fa" | "/guides/link-unlink" | "/guides/remove-restriction" | "/login" | "/otp-login" | "/panel" | "/panel/admin" | "/payment" | "/product/[slug]" | "/reseller" | "/signup" | "/spin" | "/track"
type RedirectRoutes = "/contact" | "/feed" | "/guide" | "/help" | "/index.php" | "/lol" | "/manifest.json" | "/orders" | "/privacy" | "/product/fortnite-crew-pack" | "/product/gemini-subscription" | "/product/gta6" | "/product/lego-starter-pack" | "/product/nubixshopirproductstelegram-premium-3" | "/product/v-bucks" | "/products/battlepass" | "/products/chatgpt" | "/products/crewpack" | "/products/fortnite-starter-pack" | "/products/gemini" | "/products/product_vbucks" | "/products/spotify" | "/products/starterpack" | "/terms"
type RewriteRoutes = "/api/[[...path]]" | "/media/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/api/currency-rates": {}
  "/api/test-curl": {}
  "/blog/feed.xml": {}
  "/checkout": {}
  "/contact": {}
  "/email-login": {}
  "/feed": {}
  "/forgot-password": {}
  "/guide": {}
  "/guides/disable-2fa": {}
  "/guides/link-unlink": {}
  "/guides/remove-restriction": {}
  "/help": {}
  "/index.php": {}
  "/login": {}
  "/lol": {}
  "/manifest.json": {}
  "/media/[[...path]]": { "path"?: string[]; }
  "/orders": {}
  "/otp-login": {}
  "/panel": {}
  "/panel/admin": {}
  "/payment": {}
  "/privacy": {}
  "/product/[slug]": { "slug": string; }
  "/product/fortnite-crew-pack": {}
  "/product/gemini-subscription": {}
  "/product/gta6": {}
  "/product/lego-starter-pack": {}
  "/product/nubixshopirproductstelegram-premium-3": {}
  "/product/v-bucks": {}
  "/products/battlepass": {}
  "/products/chatgpt": {}
  "/products/crewpack": {}
  "/products/fortnite-starter-pack": {}
  "/products/gemini": {}
  "/products/product_vbucks": {}
  "/products/spotify": {}
  "/products/starterpack": {}
  "/reseller": {}
  "/signup": {}
  "/spin": {}
  "/terms": {}
  "/track": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/checkout": never
  "/email-login": never
  "/forgot-password": never
  "/guides/disable-2fa": never
  "/guides/link-unlink": never
  "/guides/remove-restriction": never
  "/login": never
  "/otp-login": never
  "/panel": never
  "/panel/admin": never
  "/payment": never
  "/product/[slug]": never
  "/reseller": never
  "/signup": never
  "/spin": never
  "/track": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
