var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/panel/admin/ai-playground/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g3uy_8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_01fc9oy.js")
R.c("server/chunks/ssr/[root-of-the-server]__0um8i3u._.js")
R.c("server/chunks/ssr/node_modules_next_dist_05qu9g0._.js")
R.c("server/chunks/ssr/_04j38nu._.js")
R.c("server/chunks/ssr/_1cebomd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/app_panel_layout_jsx_1eepigi._.js")
R.c("server/chunks/ssr/app_panel_admin_layout_jsx_1ikp0_i._.js")
R.c("server/chunks/ssr/_next-internal_server_app_panel_admin_ai-playground_page_actions_0dym6cu.js")
R.m(35987)
module.exports=R.m(35987).exports
