# Generated by Django 4.2.26 on 2025-11-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FORTNITE', 'Fortnite'), ('SUBSCRIPTIONS', 'اشتراک\u200cها'), ('GIFTCARDS', 'گیفت کارت\u200cها')], default='FORTNITE', max_length=32),
        ),
    ]
