# Generated by Django 4.2.26 on 2025-11-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_userprofile_avatar'),
        ('shop', '0005_add_games_category'),
    ]

    operations = [
    ]
