# Generated by Django 4.2.26 on 2025-11-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_merge_0003_userprofile_avatar_0005_add_games_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FORTNITE', 'فورتنایت'), ('AI', 'هوش مصنوعی'), ('GIFTCARDS', 'گیفت کارت\u200cها'), ('GAMES', 'بازی\u200cها'), ('SUBSCRIPTIONS', 'اشتراک\u200cها')], default='FORTNITE', max_length=32),
        ),
    ]
