# Generated by Django 4.2.26 on 2025-11-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='شماره تلفن (09xxxxxxxxx)', max_length=11)),
                ('otp_code', models.CharField(help_text='کد تایید 6 رقمی', max_length=6)),
                ('ip_address', models.GenericIPAddressField(help_text='آدرس IP درخواست\u200cکننده')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='زمان ایجاد کد')),
                ('expires_at', models.DateTimeField(help_text='زمان انقضای کد (2 دقیقه)')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='تعداد تلاش\u200cهای نامعتبر')),
                ('is_verified', models.BooleanField(default=False, help_text='آیا کد تایید شده است')),
                ('is_used', models.BooleanField(default=False, help_text='آیا از این کد برای ثبت\u200cنام استفاده شده')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', '-created_at'], name='shop_otpver_phone_n_24e27d_idx'), models.Index(fields=['phone_number', 'is_verified', 'is_used'], name='shop_otpver_phone_n_0ede85_idx')],
            },
        ),
    ]
