# Generated by Django 4.2.26 on 2025-11-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_discountcode_amount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='shop_notifi_channel_30cd52_idx',
            old_name='shop_notifi_channel_0f7107_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='shop_notifi_created_66dadf_idx',
            old_name='shop_notifi_created_4acef8_idx',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='تاریخ انقضای کد. در صورت خالی بدون انقضا.', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('registered', 'ثبت شده'), ('processing', 'در حال انجام'), ('completed', 'انجام شده'), ('needs_2fa', 'نیاز به کد 2FA'), ('canceled', 'لغو شده')], default='pending', max_length=20),
        ),
    ]
