# Generated by Django 4.2.26 on 2025-11-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_shop_notifi_channel_0f7107_idx_shop_notifi_channel_30cd52_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('registered', 'ثبت شده'), ('processing', 'در حال انجام'), ('completed', 'انجام شده'), ('needs_2fa', 'نیاز به کد 2FA'), ('invalid_info', 'اطلاعات غلط/ناقص'), ('canceled', 'لغو شده')], default='pending', max_length=20),
        ),
    ]
