# Generated by Django 4.2.26 on 2025-12-01 23:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0021_add_lira_fields_and_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='نام نمایشی نویسنده نظر', max_length=100)),
                ('rating', models.PositiveSmallIntegerField(help_text='امتیاز محصول (1 تا 5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(help_text='متن نظر')),
                ('is_approved', models.BooleanField(default=True, help_text='آیا نظر تایید شده است')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='آیا خریدار واقعی است')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='shop_produc_product_f8f2e1_idx'), models.Index(fields=['product', 'is_approved', '-created_at'], name='shop_produc_product_1f19e8_idx')],
            },
        ),
    ]
