# Generated by Django 4.2.26 on 2025-12-03 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0023_order_wallet_rewarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='reply_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='reply_text',
            field=models.TextField(blank=True, default='', help_text='پاسخ ادمین به نظر'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='reply_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
