# Generated by Codex on 2025-12-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0026_add_original_price_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderBotUpdate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(choices=[("telegram", "Telegram"), ("website_chat", "Website Chat"), ("other", "Other")], default="telegram", max_length=32)),
                ("telegram_user_id", models.CharField(blank=True, default="", max_length=32)),
                ("telegram_username", models.CharField(blank=True, default="", max_length=64)),
                ("source_message_id", models.CharField(blank=True, default="", max_length=64)),
                ("fields_changed", models.JSONField(blank=True, default=list)),
                ("summary", models.CharField(blank=True, default="", max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bot_updates", to="shop.order")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="orderbotupdate",
            index=models.Index(fields=["order", "-created_at"], name="shop_ordbot_order_created_idx"),
        ),
        migrations.AddIndex(
            model_name="orderbotupdate",
            index=models.Index(fields=["telegram_user_id", "-created_at"], name="shop_ordbot_tguser_created_idx"),
        ),
        migrations.AddIndex(
            model_name="orderbotupdate",
            index=models.Index(fields=["created_at"], name="shop_ordbot_created_idx"),
        ),
    ]

