# Generated by Django 4.2.27 on 2025-12-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_order_bot_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_test_order',
            field=models.BooleanField(default=False, help_text='سفارش تست - در آمار مالی حساب نمی\u200cشود'),
        ),
    ]
