# Generated by Django 4.2.27 on 2025-12-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_add_is_test_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_xbox_email',
            field=models.CharField(blank=True, default='', help_text='ایمیل اکانت Xbox ساخته شده', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='created_xbox_pass',
            field=models.CharField(blank=True, default='', help_text='رمز اکانت Xbox ساخته شده', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='xbox_create_account',
            field=models.BooleanField(default=False, help_text='درخواست ساخت اکانت Xbox'),
        ),
    ]
