# Generated by Django 4.2.27 on 2025-12-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_discord_ticket_models'),
        ('shop', '0029_xbox_account_fields'),
    ]

    operations = [
    ]
