# Generated by Django 4.2.27 on 2025-12-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_merge_20251222_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.PositiveIntegerField(default=0, help_text='مبلغ استرداد شده (تومان)'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_confirmed',
            field=models.BooleanField(default=False, help_text='تایید واریز مبلغ استرداد'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_date',
            field=models.DateTimeField(blank=True, help_text='تاریخ واریز استرداد', null=True),
        ),
    ]
