# Generated by Django 4.2.27 on 2025-12-21 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_add_refund_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='XboxAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='ایمیل اکانت Xbox', max_length=254, unique=True)),
                ('password', models.CharField(help_text='رمز عبور اکانت', max_length=150)),
                ('status', models.CharField(choices=[('available', 'آزاد'), ('used', 'استفاده شده'), ('reserved', 'رزرو شده')], default='available', max_length=20)),
                ('note', models.TextField(blank=True, help_text='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='تاریخ استفاده', null=True)),
                ('order', models.ForeignKey(blank=True, help_text='سفارش مرتبط', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xbox_accounts', to='shop.order')),
            ],
            options={
                'verbose_name': 'اکانت Xbox',
                'verbose_name_plural': 'آرشیو اکانت\u200cهای Xbox',
                'ordering': ['-created_at'],
            },
        ),
    ]
