# Generated by Django 4.2.27 on 2025-12-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_add_xbox_account_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='settled',
            field=models.BooleanField(default=False, help_text='تسویه شده با همکار'),
        ),
        migrations.AddField(
            model_name='order',
            name='settled_at',
            field=models.DateTimeField(blank=True, help_text='تاریخ تسویه', null=True),
        ),
    ]
