# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_add_settled_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='account_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='account_email',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='account_password',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
