# Generated by Django 4.2.30 on 2026-06-03 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0034_orderitem_account_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, help_text='نام مهمان', max_length=150)),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته شده')], default='open', max_length=20)),
                ('unread_admin', models.IntegerField(default=0, help_text='پیام\u200cهای خوانده نشده برای ادمین')),
                ('unread_user', models.IntegerField(default=0, help_text='پیام\u200cهای خوانده نشده برای کاربر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='کاربر لاگین شده (اختیاری)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نشست چت زنده',
                'verbose_name_plural': 'نشست\u200cهای چت زنده',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'کاربر/مهمان'), ('admin', 'پشتیبان')], default='user', max_length=10)),
                ('text', models.TextField(help_text='متن پیام')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shop.livechatsession')),
            ],
            options={
                'verbose_name': 'پیام چت',
                'verbose_name_plural': 'پیام\u200cهای چت',
                'ordering': ['created_at'],
            },
        ),
    ]
