# Generated by Django 4.2.30 on 2026-06-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_livechatsession_livechatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechatmessage',
            name='file_url',
            field=models.CharField(blank=True, default='', help_text='آدرس فایل رسانه (تصویر/ویدیو/صوت)', max_length=500),
        ),
        migrations.AddField(
            model_name='livechatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'متن'), ('image', 'تصویر'), ('video', 'ویدیو'), ('audio', 'صوتی')], default='text', help_text='نوع پیام', max_length=10),
        ),
        migrations.AlterField(
            model_name='livechatmessage',
            name='text',
            field=models.TextField(blank=True, default='', help_text='متن پیام یا کپشن رسانه'),
        ),
    ]
