# Generated by Django 4.2.27 on 2026-06-07 17:00

from django.db import migrations, models


def backfill_updated_at(apps, schema_editor):
    XboxAccount = apps.get_model("shop", "XboxAccount")
    db_alias = schema_editor.connection.alias
    for account in XboxAccount.objects.using(db_alias).all().iterator():
        if account.created_at:
            XboxAccount.objects.using(db_alias).filter(pk=account.pk).update(updated_at=account.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0036_chat_media_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="xboxaccount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, blank=True, help_text="آخرین بروزرسانی", null=True),
        ),
        migrations.RunPython(backfill_updated_at, migrations.RunPython.noop),
    ]
