# Generated by Django 4.2.30 on 2026-06-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_xboxaccount_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='xboxaccount',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'اکانت Xbox', 'verbose_name_plural': 'آرشیو اکانت\u200cهای Xbox'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='group_fa',
            field=models.CharField(blank=True, default='', help_text='گروه واریانت (مثلاً اشتراک تک\u200cکاربره / گروهی)', max_length=120),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
