# Generated by Django 4.2.30 on 2026-06-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['display_order', '-id']},
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='ترتیب نمایش در ویترین/صفحه اصلی (کمتر = بالاتر)'),
        ),
    ]
