# Generated by Django 4.2.30 on 2026-06-16 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0039_alter_product_options_product_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_code', models.CharField(db_index=True, help_text='کد یکتای سلر (NS-XXXX)', max_length=16, unique=True)),
                ('token_hash', models.CharField(db_index=True, help_text='sha256 توکن ۱۶ رقمی', max_length=64, unique=True)),
                ('token_prefix', models.CharField(default='', help_text='چهار رقم اول توکن برای جستجوی ادمین', max_length=4)),
                ('status', models.CharField(choices=[('draft', 'ناقص'), ('pending_review', 'در انتظار تأیید'), ('verified', 'تأیید شده'), ('rejected', 'رد شده'), ('suspended', 'تعلیق')], default='draft', max_length=20)),
                ('support_name', models.CharField(blank=True, default='', help_text='نام اکانت پشتیبانی (نام نمایشی اصلی)', max_length=80)),
                ('shop_link', models.URLField(blank=True, default='', help_text='لینک شاپ تلگرام')),
                ('channel_link', models.URLField(blank=True, default='', help_text='لینک کانال تلگرام (باید +500 ممبر داشته باشد)')),
                ('channel_members_estimated', models.PositiveIntegerField(default=0, help_text='تعداد اعضای تخمینی کانال (از t.me/s/)')),
                ('channel_checked_at', models.DateTimeField(blank=True, help_text='آخرین زمان چک تعداد اعضا', null=True)),
                ('legal_name', models.CharField(blank=True, default='', help_text='نام و نام خانوادگی', max_length=120)),
                ('national_id', models.CharField(blank=True, default='', help_text='کد ملی ۱۰ رقمی', max_length=10)),
                ('contact_phone', models.CharField(blank=True, default='', help_text='شماره تماس', max_length=15)),
                ('bank_card_number', models.CharField(blank=True, default='', help_text='شماره کارت ۱۶ رقمی', max_length=20)),
                ('bank_sheba', models.CharField(blank=True, default='', help_text='شماره شبا (IR + 24 رقم)', max_length=26)),
                ('bank_holder', models.CharField(blank=True, default='', help_text='نام صاحب حساب', max_length=120)),
                ('wallet_balance', models.PositiveIntegerField(default=0, help_text='موجودی کیف پول (تومان)')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, default='', help_text='یادداشت داخلی ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reseller_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل همکار',
                'verbose_name_plural': 'پروفایل همکاران',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='is_reseller_order',
            field=models.BooleanField(db_index=True, default=False, help_text='سفارش ثبت شده توسط همکار'),
        ),
        migrations.AddField(
            model_name='order',
            name='reseller_seller_code',
            field=models.CharField(blank=True, default='', help_text='کد سلر (NS-XXXX) هنگام ثبت سفارش همکار', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('registered', 'ثبت شده'), ('processing', 'در حال انجام'), ('completed', 'انجام شده'), ('needs_2fa', 'نیاز به کد 2FA'), ('needs_tr_region', 'نیاز به تغییر ریجن به ترکیه'), ('invalid_info', 'اطلاعات غلط/ناقص'), ('canceled', 'لغو شده'), ('refunded', 'مسترد شده'), ('wallet_topup', 'شارژ کیف پول همکار')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('reseller', 'Reseller')], default='user', max_length=16),
        ),
        migrations.CreateModel(
            name='ResellerPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveSmallIntegerField(default=1, help_text='حداقل تعداد برای فعال شدن این قیمت')),
                ('price', models.PositiveIntegerField(help_text='قیمت به ازای هر واحد در این پله (تومان)')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_tiers', to='shop.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reseller_tiers', to='shop.productvariant')),
            ],
            options={
                'verbose_name': 'پله قیمت همکار',
                'verbose_name_plural': 'پله\u200cهای قیمت همکار',
                'ordering': ['product_id', 'variant_id', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='ResellerWalletTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('topup_pending', 'شارژ در انتظار پرداخت'), ('topup', 'شارژ کیف پول'), ('order', 'خرید سفارش'), ('refund', 'بازگشت سفارش'), ('adjust', 'تعدیل دستی')], max_length=20)),
                ('amount', models.IntegerField(help_text='مقدار تراکنش (تومان)؛ مثبت = افزایش، منفی = کاهش')),
                ('balance_after', models.PositiveIntegerField(default=0, help_text='موجودی بعد از اعمال')),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reseller_wallet_actions', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_txns', to='shop.resellerprofile')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.payment')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول همکار',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول همکار',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', '-created_at'], name='shop_reseller_txn_profile_idx'), models.Index(fields=['kind', '-created_at'], name='shop_reseller_txn_kind_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='resellerprofile',
            index=models.Index(fields=['status', '-updated_at'], name='shop_reseller_stat_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerprofile',
            index=models.Index(fields=['seller_code'], name='shop_reseller_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='resellerpricetier',
            constraint=models.UniqueConstraint(fields=('product', 'variant', 'min_quantity'), name='shop_reseller_tier_unique'),
        ),
    ]
