# Generated by Django 4.2.30 on 2026-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_seed_reseller_crewpack_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechatmessage',
            name='is_ai',
            field=models.BooleanField(default=False, help_text='پاسخ تولیدشده توسط دستیار هوش مصنوعی'),
        ),
    ]
