# Generated by Django 4.2.30 on 2026-06-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_livechatmessage_is_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list, help_text='فیلدهای اطلاعات مشتری: [{key, label, type, required, placeholder, options?}]'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_text',
            field=models.TextField(blank=True, default='', help_text='متن نحوه تحویل (هر خط = یک مرحله). اگر خالی باشد، متن پیش\u200cفرض نمایش داده می\u200cشود.'),
        ),
        migrations.AddField(
            model_name='product',
            name='disable_2fa_color',
            field=models.CharField(default='amber', help_text='رنگ بنر 2FA: amber | blue | gray | red', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='disable_2fa_text',
            field=models.CharField(blank=True, default='', help_text='متن سفارشی بنر 2FA (اختیاری)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='faq',
            field=models.JSONField(blank=True, default=list, help_text='لیست سوالات متداول: [{q: str, a: str}]'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_2fa',
            field=models.BooleanField(default=False, help_text='آیا این محصول نیاز به خاموش کردن 2FA دارد؟'),
        ),
    ]
