# Generated by Django 4.2.30 on 2026-06-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_product_custom_fields_product_delivery_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, default='', help_text='زیردسته (کلید: ps, steam, xbox, ...)', max_length=50),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='کلید زیردسته (مثلاً ps, steam, xbox)', max_length=50)),
                ('label', models.CharField(help_text='نام نمایشی (مثلاً پلی\u200cاستیشن)', max_length=100)),
                ('category', models.CharField(choices=[('FORTNITE', 'فورتنایت'), ('AI', 'هوش مصنوعی'), ('GIFTCARDS', 'گیفت کارت\u200cها'), ('GAMES', 'بازی\u200cها'), ('SUBSCRIPTIONS', 'اشتراک\u200cها')], help_text='دسته\u200cبندی والد', max_length=32)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش (کمتر = بالاتر)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'زیردسته',
                'verbose_name_plural': 'زیردسته\u200cها',
                'ordering': ['category', 'display_order', 'id'],
                'unique_together': {('key', 'category')},
            },
        ),
    ]
