# Generated by Django 4.2.30 on 2026-06-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_product_subcategory_and_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='resellerprofile',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='ایمیل دریافت نوتیفیکیشن\u200cهای سفارش', max_length=254),
        ),
    ]
