# Generated by Django 4.2.30 on 2026-06-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_reseller_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='xboxaccount',
            name='owner_label',
            field=models.CharField(blank=True, default='', help_text='نام مالک (برای ورودی دستی بدون سفارش)', max_length=120),
        ),
        migrations.AddField(
            model_name='xboxaccount',
            name='owner_phone',
            field=models.CharField(blank=True, default='', help_text='شماره مالک (برای ورودی دستی بدون سفارش)', max_length=20),
        ),
    ]
