# Generated by Django 4.2.30 on 2026-06-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_xboxaccount_owner_label_xboxaccount_owner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='resellerprofile',
            name='low_balance_threshold',
            field=models.PositiveIntegerField(default=0, help_text='آستانه هشدار موجودی کم (تومان)؛ صفر = غیرفعال'),
        ),
        migrations.AddField(
            model_name='resellerprofile',
            name='referral_rewarded',
            field=models.BooleanField(default=False, help_text='آیا پاداش معرف برای این همکار پرداخت شده'),
        ),
        migrations.AddField(
            model_name='resellerprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='همکاری که این همکار را معرفی کرده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='shop.resellerprofile'),
        ),
    ]
