# Generated by Django 4.2.30 on 2026-06-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_orderitemaccount_and_order_reserve_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
