# Generated by Django 4.2.30 on 2026-06-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_seed_reseller_tiers_all_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='daily_order_limit',
            field=models.PositiveIntegerField(default=0, help_text='حداکثر تعداد سفارش مجاز در روز (۰ برای بدون محدودیت)', verbose_name='محدودیت تعداد سفارش روزانه'),
        ),
        migrations.AddField(
            model_name='product',
            name='ordering_disabled',
            field=models.BooleanField(default=False, help_text='با فعال کردن این گزینه، ثبت سفارش این محصول برای مشتریان و همکاران متوقف می\u200cشود.', verbose_name='غیرفعال کردن ثبت سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitemaccount',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تکمیل مشخصات'), ('filled', 'آماده انجام (مشخصات ثبت شده)')], default='pending', max_length=16),
        ),
    ]
