# Generated by Django 4.2.30 on 2026-06-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_product_daily_order_limit_product_ordering_disabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer_daily_order_limit',
            field=models.PositiveIntegerField(default=0, help_text='حداکثر تعداد سفارش مجاز مشتریان عادی در روز (۰ برای بدون محدودیت)', verbose_name='محدودیت تعداد سفارش روزانه مشتریان'),
        ),
        migrations.AddField(
            model_name='product',
            name='customer_ordering_disabled',
            field=models.BooleanField(default=False, help_text='با فعال کردن این گزینه، ثبت سفارش این محصول برای مشتریان عادی متوقف می\u200cشود.', verbose_name='غیرفعال کردن سفارش مشتریان'),
        ),
        migrations.AddField(
            model_name='product',
            name='reseller_daily_order_limit',
            field=models.PositiveIntegerField(default=0, help_text='حداکثر تعداد سفارش مجاز همکاران در روز (۰ برای بدون محدودیت)', verbose_name='محدودیت تعداد سفارش روزانه همکاران'),
        ),
        migrations.AddField(
            model_name='product',
            name='reseller_ordering_disabled',
            field=models.BooleanField(default=False, help_text='با فعال کردن این گزینه، ثبت سفارش این محصول برای همکاران متوقف می\u200cشود.', verbose_name='غیرفعال کردن سفارش همکاران'),
        ),
    ]
