# Generated by Django 4.2.30 on 2026-06-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_product_customer_daily_order_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customer_daily_order_limit',
            field=models.IntegerField(default=-1, help_text='حداکثر تعداد سفارش مجاز مشتریان عادی در روز (-۱ برای بدون محدودیت)', verbose_name='محدودیت تعداد سفارش روزانه مشتریان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='daily_order_limit',
            field=models.IntegerField(default=-1, help_text='حداکثر تعداد سفارش مجاز در روز (-۱ برای بدون محدودیت)', verbose_name='محدودیت تعداد سفارش روزانه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reseller_daily_order_limit',
            field=models.IntegerField(default=-1, help_text='حداکثر تعداد سفارش مجاز همکاران در روز (-۱ برای بدون محدودیت)', verbose_name='محدودیت تعداد سفارش روزانه همکاران'),
        ),
    ]
