# Generated by Django 4.2.30 on 2026-06-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_alter_product_customer_daily_order_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemaccount',
            name='settled',
            field=models.BooleanField(default=False, help_text='تسویه شده'),
        ),
        migrations.AddField(
            model_name='orderitemaccount',
            name='settled_at',
            field=models.DateTimeField(blank=True, help_text='تاریخ تسویه واحد', null=True),
        ),
        migrations.AddField(
            model_name='orderitemaccount',
            name='unit_tracking',
            field=models.CharField(blank=True, help_text='کد رهگیری واحد (مثلا 7153-1)', max_length=20, null=True, unique=True),
        ),
    ]
