# Generated by Django 4.2.30 on 2026-06-30 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0055_orderitemaccount_settled_orderitemaccount_settled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='اگر تنظیم شود، فقط همین کاربر می\u200cتواند کد را استفاده کند.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='حداکثر دفعات استفاده. خالی = نامحدود', null=True),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='single_use',
            field=models.BooleanField(default=False, help_text='فقط یک\u200cبار قابل استفاده'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='source',
            field=models.CharField(default='manual', help_text='manual | spin | referral | milestone', max_length=20),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points_balance',
            field=models.PositiveIntegerField(default=0, help_text='امتیاز قابل مصرف کاربر'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='کد معرف یکتای کاربر (مثلاً NX-AB12CD)', max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='کاربری که این کاربر را معرفی کرده است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spin_used',
            field=models.BooleanField(default=False, help_text='آیا کاربر از چرخش رایگان هفته\u200cی لانچ استفاده کرده است؟'),
        ),
        migrations.CreateModel(
            name='SpinResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_index', models.PositiveSmallIntegerField(default=0)),
                ('segment_type', models.CharField(help_text='blank | wallet | discount5 | discount20', max_length=20)),
                ('prize_label', models.CharField(blank=True, default='', max_length=120)),
                ('wallet_credit', models.PositiveIntegerField(default=0)),
                ('public_name', models.CharField(blank=True, default='', help_text='نام ناشناس\u200cشده برای نمایش عمومی', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin_results', to='shop.discountcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='shop_spin_recent_idx')],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_source', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referrer', '-created_at'], name='shop_referral_referrer_idx')],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='مثبت = کسب، منفی = مصرف')),
                ('reason', models.CharField(choices=[('purchase', 'خرید'), ('referral', 'معرفی'), ('spin_cost', 'هزینه گردونه'), ('milestone', 'جایزه پلکانی'), ('adjust', 'تعدیل دستی')], max_length=20)),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_txns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='shop_points_user_idx')],
            },
        ),
    ]
