# Generated by Django 4.2.30 on 2026-06-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_blogcategory_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='diamonds_used',
            field=models.PositiveIntegerField(default=0, help_text='تعداد الماس مصرف\u200cشده برای تخفیف این سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wallet_rewarded',
            field=models.BooleanField(default=False, help_text='[منسوخ] کش\u200cبک کیف پول حذف شده؛ این فیلد فقط تاریخی است'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wallet_used',
            field=models.PositiveIntegerField(default=0, help_text='[منسوخ] فقط برای سفارش\u200cهای قدیمی قبل از حذف کیف پول'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='reason',
            field=models.CharField(choices=[('purchase', 'خرید'), ('referral', 'معرفی'), ('spin_cost', 'هزینه گردونه'), ('spin_win', 'جایزه گردونه'), ('milestone', 'جایزه پلکانی'), ('redeem', 'تبدیل به تخفیف خرید'), ('adjust', 'تعدیل دستی')], max_length=20),
        ),
    ]
