# Generated by Django 4.2.30 on 2026-07-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_migrate_wallet_balance_to_diamonds'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ تسویه')),
                ('total_amount', models.PositiveIntegerField(default=0, help_text='مبلغ کل تسویه شده')),
                ('total_lira', models.FloatField(default=0.0, help_text='لیر کل تسویه شده')),
                ('order_count', models.PositiveIntegerField(default=0, help_text='تعداد سفارش\u200cها')),
                ('orders', models.ManyToManyField(help_text='سفارش\u200cهای تسویه شده در این دوره', related_name='settlement_batches', to='shop.order')),
            ],
            options={
                'verbose_name': 'تاریخچه تسویه',
                'verbose_name_plural': 'تاریخچه\u200cهای تسویه',
                'ordering': ['-created_at'],
            },
        ),
    ]
