# Generated by Django 4.2.30 on 2026-07-01 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0060_settlementbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_global', models.BooleanField(default=False, help_text='True if this is a general announcement for all users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Only used for per-user notifications')),
                ('user', models.ForeignKey(blank=True, help_text='Null for global announcements', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اعلان سایت',
                'verbose_name_plural': 'اعلان\u200cهای سایت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteNotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='shop.sitenotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اعلان خوانده شده',
                'verbose_name_plural': 'اعلان\u200cهای خوانده شده',
                'unique_together': {('user', 'notification')},
            },
        ),
    ]
