# Generated by Django 4.2.30 on 2026-07-02 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0061_sitenotification_sitenotificationread'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام محصول درخواستی')),
                ('contact_info', models.CharField(max_length=255, verbose_name='اطلاعات تماس (ایمیل/تلفن)')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('PROCESSED', 'تهیه شده'), ('REJECTED', 'غیرقابل تهیه')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'درخواست محصول',
                'verbose_name_plural': 'درخواست\u200cهای محصولات',
                'ordering': ['-created_at'],
            },
        ),
    ]
