# Generated by Django 4.2.30 on 2026-07-03 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_productrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('entry_type', models.CharField(choices=[('expense', 'خرجی (هزینه)'), ('profit', 'سود متفرقه (درآمد)')], default='expense', max_length=20, verbose_name='نوع تراکنش')),
                ('currency', models.CharField(choices=[('toman', 'تومان'), ('usd', 'دلار (USD)')], default='toman', max_length=10, verbose_name='واحد پولی')),
                ('amount', models.FloatField(default=0.0, verbose_name='مبلغ')),
                ('created_rate', models.IntegerField(default=0, verbose_name='نرخ دلار زمان ثبت (تومان)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('note', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تراکنش حسابداری متفرقه',
                'verbose_name_plural': 'تراکنش\u200cهای حسابداری متفرقه',
                'ordering': ['-created_at'],
            },
        ),
    ]
