# Generated by Django 4.2.30 on 2026-07-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_accountingtransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resellerpricetier',
            options={'ordering': ['product_id', 'variant_id', 'reseller_id', 'min_quantity'], 'verbose_name': 'پله قیمت همکار', 'verbose_name_plural': 'پله\u200cهای قیمت همکار'},
        ),
        migrations.RemoveConstraint(
            model_name='resellerpricetier',
            name='shop_reseller_tier_unique',
        ),
        migrations.AddField(
            model_name='resellerpricetier',
            name='reseller',
            field=models.ForeignKey(blank=True, help_text='خالی = پله\u200cی عمومی؛ در غیر این صورت override اختصاصی همین همکار', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_overrides', to='shop.resellerprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reseller_pricing_tour_seen_at',
            field=models.DateTimeField(blank=True, help_text='آخرین زمان مشاهده\u200cی تور آموزشی قیمت\u200cگذاری همکاران توسط ادمین؛ null = هنوز دیده نشده', null=True),
        ),
        migrations.AddConstraint(
            model_name='resellerpricetier',
            constraint=models.UniqueConstraint(fields=('product', 'variant', 'min_quantity', 'reseller'), name='shop_reseller_tier_unique'),
        ),
    ]
