# Generated by Django 4.2.30 on 2026-07-07 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0064_alter_resellerpricetier_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='برای مهمان: شناسه پایدار در localStorage', max_length=64)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('items', models.JSONField(blank=True, default=list)),
                ('item_count', models.PositiveSmallIntegerField(default=0)),
                ('total_value', models.PositiveIntegerField(default=0, help_text='تومان')),
                ('last_product_page', models.CharField(blank=True, default='', max_length=300)),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveSmallIntegerField(default=0)),
                ('converted_at', models.DateTimeField(blank=True, help_text='وقتی کاربر نهایتاً سفارش ثبت کرد', null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=240)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abandoned_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سبد رها\u200cشده',
                'verbose_name_plural': 'سبدهای رها\u200cشده',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['converted_at', '-last_seen_at'], name='shop_abncart_conv_lsa_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='abandonedcart',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='shop_abncart_user_unique'),
        ),
    ]
