# Generated by Django 4.2.30 on 2026-07-09 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_abandonedcart_abandonedcart_shop_abncart_user_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='G4A4MarkupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True, verbose_name='نام دسته\u200cبندی G4A4')),
                ('markup_percent', models.FloatField(default=10.0, verbose_name='درصد سود (مثلاً ۱۵.۵)')),
            ],
            options={
                'verbose_name': 'قانون سود G4A4',
                'verbose_name_plural': 'قوانین سود G4A4',
            },
        ),
        migrations.CreateModel(
            name='G4A4Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_product_id', models.IntegerField(unique=True, verbose_name='شناسه محصول خارجی')),
                ('category', models.CharField(max_length=200, verbose_name='دسته\u200cبندی G4A4')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('game_slug', models.SlugField(max_length=200, verbose_name='اسلاگ بازی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال برای نمایش در سایت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محصول G4A4',
                'verbose_name_plural': 'محصولات G4A4',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_fields_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='اطلاعات فیلدهای دلخواه'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='g4a4_order_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='شناسه سفارش G4A4'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='g4a4_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='وضعیت سفارش G4A4'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.product'),
        ),
        migrations.CreateModel(
            name='G4A4Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_variation_id', models.IntegerField(unique=True, verbose_name='شناسه واریانت خارجی')),
                ('name', models.CharField(max_length=255, verbose_name='نام واریانت')),
                ('cost_irt', models.PositiveIntegerField(verbose_name='قیمت خرید از G4A4 (تومان)')),
                ('sell_toman', models.PositiveIntegerField(verbose_name='قیمت فروش ما (تومان)')),
                ('in_stock', models.BooleanField(default=True, verbose_name='موجود')),
                ('delivery_type', models.CharField(blank=True, max_length=50, verbose_name='نوع تحویل')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='ریجن')),
                ('required_fields', models.JSONField(blank=True, default=list, verbose_name='فیلدهای مورد نیاز')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='ویژگی\u200cها')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='shop.g4a4product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'واریانت G4A4',
                'verbose_name_plural': 'واریانت\u200cهای G4A4',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='g4a4_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.g4a4variation', verbose_name='واریانت G4A4'),
        ),
    ]
