# Generated by Django 4.2.30 on 2026-07-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_userprofile_referral_notified_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reseller_info_updated',
            field=models.BooleanField(default=False, help_text='اطلاعات سفارش توسط همکار ویرایش شده و نیاز به بررسی مجدد دارد'),
        ),
    ]
