# Generated by Django 4.2.30 on 2026-07-09 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0066_g4a4markuprule_g4a4product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('g4a4_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='shop.g4a4product')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آیتم علاقه\u200cمندی',
                'verbose_name_plural': 'لیست علاقه\u200cمندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CustomerWalletTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('topup_pending', 'شارژ در انتظار پرداخت'), ('topup', 'شارژ کیف پول'), ('order', 'خرید سفارش'), ('refund', 'بازگشت سفارش'), ('adjust', 'تعدیل دستی')], max_length=20)),
                ('amount', models.IntegerField(help_text='مقدار تراکنش (تومان)؛ مثبت = افزایش، منفی = کاهش')),
                ('balance_after', models.PositiveIntegerField(default=0, help_text='موجودی بعد از اعمال')),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_wallet_actions', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_txns', to='shop.userprofile')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.payment')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول مشتری',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول مشتری',
                'ordering': ['-created_at'],
            },
        ),
    ]
