# Generated by Django 4.2.30 on 2026-07-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_order_reseller_info_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_16_9',
            field=models.URLField(blank=True, help_text='کاور 16:9 محصول (تصویر بزرگ در صفحه محصول)'),
        ),
    ]
