# Generated by Django 4.2.30 on 2026-07-09 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0067_wishlistitem_customerwallettxn'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('fortnite', 'Fortnite'), ('cod-mobile', 'Call of Duty: Mobile'), ('wild-rift', 'League of Legends: Wild Rift'), ('clash-royale', 'Clash Royale'), ('pubg', 'PUBG Mobile'), ('coc', 'Clash of Clans'), ('free-fire', 'Free Fire'), ('ml', 'Mobile Legends'), ('brawl', 'Brawl Stars'), ('xbox', 'Xbox Live Account'), ('ps', 'PlayStation Network Account'), ('steam', 'Steam Account')], max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.BigIntegerField(help_text='قیمت فروش (تومان)')),
                ('platform', models.CharField(blank=True, default='', max_length=64)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_review', 'در انتظار تایید ادمین'), ('published', 'منتشر شده'), ('reserved', 'رزرو شده (در حال خرید)'), ('sold', 'فروخته شده'), ('rejected', 'رد شده'), ('expired', 'منقضی شده')], default='pending_review', max_length=20)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('is_featured', models.BooleanField(default=False, help_text='آگهی ویژه / نردبان شده')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آگهی فروش اکانت',
                'verbose_name_plural': 'آگهی\u200cهای فروش اکانت',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, help_text='موجودی قابل برداشت فروشنده (تومان)')),
                ('sheba', models.CharField(blank=True, default='', max_length=26)),
                ('card_number', models.CharField(blank=True, default='', max_length=16)),
                ('owner_name', models.CharField(blank=True, default='', max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کیف پول فروشنده',
                'verbose_name_plural': 'کیف پول\u200cهای فروشندگان',
            },
        ),
        migrations.CreateModel(
            name='SellerWalletTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sale', 'فروش آگهی'), ('withdrawal_pending', 'درخواست تسویه'), ('withdrawal', 'تسویه حساب موفق'), ('withdrawal_rejected', 'رد تسویه حساب'), ('adjust', 'تعدیل دستی')], max_length=20)),
                ('amount', models.IntegerField(help_text='مثبت = افزایش موجودی، منفی = کاهش/تسویه')),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txns', to='shop.sellerwallet')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول فروشنده',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول فروشندگان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='shop.accountlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گزارش تخلف آگهی',
                'verbose_name_plural': 'گزارش\u200cهای تخلف آگهی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('order', models.SmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.accountlisting')),
            ],
            options={
                'verbose_name': 'تصویر آگهی',
                'verbose_name_plural': 'تصاویر آگهی\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccountDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(help_text='مبلغ معامله (تومان)')),
                ('commission', models.BigIntegerField(help_text='کارمزد سایت (تومان)')),
                ('status', models.CharField(choices=[('initiated', 'ایجاد شده (در انتظار پرداخت)'), ('paid', 'پرداخت شده (پول نزد سایت)'), ('credentials_sent', 'ارسال مشخصات توسط فروشنده'), ('buyer_confirmed', 'تایید نهایی خریدار'), ('released', 'تسویه شده با فروشنده'), ('disputed', 'دارای اختلاف'), ('refunded', 'برگشت وجه به خریدار'), ('cancelled', 'لغو شده')], default='initiated', max_length=24)),
                ('credentials_encrypted', models.TextField(blank=True, default='')),
                ('auto_release_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.livechatsession')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='shop.accountlisting')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.payment')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'معامله امن',
                'verbose_name_plural': 'معاملات امن',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='shop.accountlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'علاقه\u200cمندی آگهی',
                'verbose_name_plural': 'علاقه\u200cمندی\u200cهای آگهی\u200cها',
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
