# Generated by Django 4.2.30 on 2026-07-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_accountlisting_sellerwallet_sellerwallettxn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='national_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='national_cards/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='national_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'تایید نشده'), ('pending', 'در انتظار بررسی'), ('verified', 'تایید شده'), ('rejected', 'رد شده')], default='unverified', max_length=20),
        ),
    ]
