# Generated by Django 4.2.30 on 2026-07-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_add_cover_16_9'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='info_corrected',
            field=models.BooleanField(default=False, help_text='اطلاعات سفارش توسط کاربر اصلاح شده و در پنل ادمین پین شده است'),
        ),
        migrations.AddField(
            model_name='order',
            name='info_corrected_at',
            field=models.DateTimeField(blank=True, help_text='زمان اصلاح اطلاعات توسط کاربر', null=True),
        ),
    ]
