# Generated by Django 4.2.30 on 2026-07-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0069_userprofile_national_card_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wordpress_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='شناسه محصول در فروشگاه وردپرس برای همگام\u200cسازی بدون ساخت رکورد تکراری', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wordpress_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wordpress_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='wordpress_comment_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='wordpress_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wordpress_user_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
