# Generated by Django 4.2.30 on 2026-07-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_product_wordpress_id_product_wordpress_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='jinx_image',
            field=models.CharField(blank=True, default='', help_text='آدرس تصویر سفارشی جینکس', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='jinx_text',
            field=models.TextField(blank=True, default='', help_text='متن دیالوگ سفارشی جینکس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='diamonds_used',
            field=models.PositiveIntegerField(default=0, help_text='تعداد کوین مصرف\u200cشده برای تخفیف این سفارش'),
        ),
    ]
