# Generated by Django 4.2.30 on 2026-07-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0071_product_jinx_image_product_jinx_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page_customization',
            field=models.JSONField(blank=True, default=dict, help_text='تنظیمات سفارشیسازی صفحه محصول'),
        ),
    ]
