# Generated by Django 4.2.30 on 2026-07-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0072_live_chat_typing_presence"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialWeekClosure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("week_start", models.DateField(help_text="شنبه شروع هفته مالی", unique=True)),
                ("week_end", models.DateField(help_text="جمعه پایان هفته مالی")),
                ("gross_revenue", models.PositiveBigIntegerField(default=0)),
                ("refunds", models.PositiveBigIntegerField(default=0)),
                ("purchase_cost", models.PositiveBigIntegerField(default=0)),
                ("fixed_cost_share", models.PositiveBigIntegerField(default=0)),
                ("other_expenses", models.PositiveBigIntegerField(default=0)),
                ("other_income", models.PositiveBigIntegerField(default=0)),
                ("special_profit", models.BigIntegerField(default=0)),
                ("net_profit", models.BigIntegerField(default=0)),
                ("lira_rate", models.PositiveIntegerField(default=0)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("closed_at", models.DateTimeField(auto_now_add=True)),
                ("closed_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="financial_week_closures", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "بستن پرونده مالی هفتگی",
                "verbose_name_plural": "پرونده‌های مالی هفتگی",
                "ordering": ["-week_start"],
            },
        ),
    ]
