# Generated by Django 4.2.30 on 2026-07-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0072_product_page_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FORTNITE', 'فورتنایت'), ('AI', 'هوش مصنوعی'), ('GIFTCARDS', 'گیفت کارت\u200cها'), ('GAMES', 'بازی\u200cها'), ('SUBSCRIPTIONS', 'اشتراک\u200cها'), ('ACCOUNTS', 'بازارچه اکانت\u200cها')], default='FORTNITE', max_length=32),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(choices=[('FORTNITE', 'فورتنایت'), ('AI', 'هوش مصنوعی'), ('GIFTCARDS', 'گیفت کارت\u200cها'), ('GAMES', 'بازی\u200cها'), ('SUBSCRIPTIONS', 'اشتراک\u200cها'), ('ACCOUNTS', 'بازارچه اکانت\u200cها')], help_text='دسته\u200cبندی والد', max_length=32),
        ),
    ]
