# Generated by Django 4.2.30 on 2026-07-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0073_alter_product_category_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlisting',
            name='payment_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_fee_orders', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='accountlisting',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('payment_pending', 'در انتظار پرداخت حق مزد'), ('pending_review', 'در انتظار تایید ادمین'), ('published', 'منتشر شده'), ('reserved', 'رزرو شده (در حال خرید)'), ('sold', 'فروخته شده'), ('rejected', 'رد شده'), ('expired', 'منقضی شده')], default='payment_pending', max_length=20),
        ),
    ]
