# Generated by Django 4.2.30 on 2026-07-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0076_accountlisting_private_attributes_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FORTNITE', 'فورتنایت'), ('INGAME', 'جم و یوسی بازی\u200cها'), ('AI', 'هوش مصنوعی'), ('GIFTCARDS', 'گیفت کارت\u200cها'), ('BATTLENET', 'محصولات بتل نت'), ('GAMES', 'بازی\u200cها'), ('SUBSCRIPTIONS', 'اشتراک\u200cها'), ('ACCOUNTS', 'بازارچه اکانت\u200cها')], default='FORTNITE', max_length=32),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(choices=[('FORTNITE', 'فورتنایت'), ('INGAME', 'جم و یوسی بازی\u200cها'), ('AI', 'هوش مصنوعی'), ('GIFTCARDS', 'گیفت کارت\u200cها'), ('BATTLENET', 'محصولات بتل نت'), ('GAMES', 'بازی\u200cها'), ('SUBSCRIPTIONS', 'اشتراک\u200cها'), ('ACCOUNTS', 'بازارچه اکانت\u200cها')], help_text='دسته\u200cبندی والد', max_length=32),
        ),
    ]
