# Generated by Django 4.2.30 on 2026-08-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0077_add_ticketmessage_is_admin_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='refund_credit',
            field=models.PositiveIntegerField(default=0, help_text='اعتبار بازگشتی (تومان) حاصل از استرداد سفارش — قابل مصرف کامل در خرید بعدی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FORTNITE', 'فورتنایت'), ('PUBG', 'پابجی'), ('COD_MOBILE', 'کالاف دیوتی'), ('CLASH_ROYALE', 'کلش رویال'), ('CLASH_OF_CLANS', 'کلش اف کلنز'), ('BRAWL_STARS', 'براول استارز'), ('FREE_FIRE', 'فری فایر'), ('VALORANT', 'ولورانت'), ('RAINBOW_SIX', 'رینبو سیکس'), ('MARVEL_RIVALS', 'مارول ریوالز'), ('PING_REDUCTION', 'سرویس کاهش پینگ'), ('MOBILE_GAMES', 'بازی\u200cهای موبایل'), ('ROCKET_LEAGUE', 'راکت لیگ'), ('AI', 'هوش مصنوعی'), ('GIFTCARDS', 'گیفت کارت\u200cها'), ('GAMES', 'بازی\u200cها'), ('SUBSCRIPTIONS', 'اشتراک\u200cها')], default='FORTNITE', max_length=32),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(choices=[('FORTNITE', 'فورتنایت'), ('PUBG', 'پابجی'), ('COD_MOBILE', 'کالاف دیوتی'), ('CLASH_ROYALE', 'کلش رویال'), ('CLASH_OF_CLANS', 'کلش اف کلنز'), ('BRAWL_STARS', 'براول استارز'), ('FREE_FIRE', 'فری فایر'), ('VALORANT', 'ولورانت'), ('RAINBOW_SIX', 'رینبو سیکس'), ('MARVEL_RIVALS', 'مارول ریوالز'), ('PING_REDUCTION', 'سرویس کاهش پینگ'), ('MOBILE_GAMES', 'بازی\u200cهای موبایل'), ('ROCKET_LEAGUE', 'راکت لیگ'), ('AI', 'هوش مصنوعی'), ('GIFTCARDS', 'گیفت کارت\u200cها'), ('GAMES', 'بازی\u200cها'), ('SUBSCRIPTIONS', 'اشتراک\u200cها')], help_text='دسته\u200cبندی والد', max_length=32),
        ),
    ]
