# Generated by Django 4.2.30 on 2026-08-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0078_userprofile_refund_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_credit_used',
            field=models.PositiveIntegerField(default=0, help_text='اعتبار بازگشتی (تومان) مصرف\u200cشده در این سفارش'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='reason',
            field=models.CharField(choices=[('purchase', 'خرید'), ('referral', 'معرفی'), ('spin_cost', 'هزینه گردونه'), ('spin_win', 'جایزه گردونه'), ('milestone', 'جایزه پلکانی'), ('redeem', 'تبدیل به تخفیف خرید'), ('adjust', 'تعدیل دستی'), ('refund_credit', 'اعتبار بازگشتی (استرداد سفارش)'), ('refund_use', 'مصرف اعتبار بازگشتی در خرید')], max_length=20),
        ),
    ]
