# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0079_order_refund_credit_used_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refund_credit_granted_amount",
            field=models.PositiveIntegerField(default=0, help_text="اعتبار ریالی اعطاشده بابت این ریفاند"),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_processed_at",
            field=models.DateTimeField(blank=True, help_text="زمان پردازش اعتبار ریفاند", null=True),
        ),
        migrations.CreateModel(
            name="RefundCreditTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.IntegerField(help_text="مثبت = افزایش اعتبار، منفی = مصرف اعتبار")),
                ("kind", models.CharField(choices=[("refund", "بازگشت وجه"), ("spend", "مصرف اعتبار بازگشتی"), ("restore", "بازگردانی اعتبار"), ("legacy_conversion", "تبدیل ریفاند قدیمی")], max_length=24)),
                ("balance_after", models.PositiveIntegerField(default=0)),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                ("note", models.CharField(blank=True, default="", max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("related_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="shop.order")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="refund_credit_txns", to="auth.user")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["user", "-created_at"], name="shop_refund_user_idx")],
            },
        ),
    ]
