# Generated by Django 4.2.30 on 2026-08-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0077_alter_product_category_alter_subcategory_category'),
        ('shop', '0080_refund_credit_ledger_and_order_markers'),
    ]

    operations = [
    ]
