# Generated by Django 4.2.30 on 2026-08-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0081_merge_20260807_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='custom_fields_data',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='g4a4_order_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='g4a4_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='g4a4_variation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='jinx_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='jinx_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='page_customization',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wordpress_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wordpress_modified_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wordpress_url',
        ),
        migrations.RemoveField(
            model_name='productcomment',
            name='wordpress_comment_id',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='wordpress_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='national_card_image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='national_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_reject_reason',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wordpress_user_id',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='cost',
            field=models.IntegerField(default=0, help_text='هزینه پیامک به ریال'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='provider_msg_id',
            field=models.CharField(blank=True, help_text='شناسه پیامک در کاوه\u200cنگار', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='segments',
            field=models.IntegerField(default=1, help_text='تعداد پارت\u200cهای پیامک'),
        ),
        migrations.AlterField(
            model_name='order',
            name='diamonds_used',
            field=models.PositiveIntegerField(default=0, help_text='تعداد الماس مصرف\u200cشده برای تخفیف این سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitemaccount',
            name='mode',
            field=models.CharField(choices=[('existing', 'اکانت موجود مشتری'), ('create_for_me', 'ساخت اکانت توسط جینکس فمیلی')], default='existing', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FORTNITE', 'فورتنایت'), ('PUBG', 'پابجی'), ('COD_MOBILE', 'کالاف دیوتی'), ('CLASH_ROYALE', 'کلش رویال'), ('CLASH_OF_CLANS', 'کلش اف کلنز'), ('BRAWL_STARS', 'براول استارز'), ('FREE_FIRE', 'فری فایر'), ('VALORANT', 'ولورانت'), ('RAINBOW_SIX', 'رینبو سیکس'), ('MARVEL_RIVALS', 'مارول ریوالز'), ('PING_REDUCTION', 'سرویس کاهش پینگ'), ('MOBILE_GAMES', 'بازی\u200cهای موبایل'), ('ROCKET_LEAGUE', 'راکت لیگ'), ('AI', 'هوش مصنوعی'), ('GIFTCARDS', 'گیفت کارت\u200cها'), ('GAMES', 'بازی\u200cها'), ('SUBSCRIPTIONS', 'اشتراک\u200cها')], default='FORTNITE', max_length=32),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(choices=[('FORTNITE', 'فورتنایت'), ('PUBG', 'پابجی'), ('COD_MOBILE', 'کالاف دیوتی'), ('CLASH_ROYALE', 'کلش رویال'), ('CLASH_OF_CLANS', 'کلش اف کلنز'), ('BRAWL_STARS', 'براول استارز'), ('FREE_FIRE', 'فری فایر'), ('VALORANT', 'ولورانت'), ('RAINBOW_SIX', 'رینبو سیکس'), ('MARVEL_RIVALS', 'مارول ریوالز'), ('PING_REDUCTION', 'سرویس کاهش پینگ'), ('MOBILE_GAMES', 'بازی\u200cهای موبایل'), ('ROCKET_LEAGUE', 'راکت لیگ'), ('AI', 'هوش مصنوعی'), ('GIFTCARDS', 'گیفت کارت\u200cها'), ('GAMES', 'بازی\u200cها'), ('SUBSCRIPTIONS', 'اشتراک\u200cها')], help_text='دسته\u200cبندی والد', max_length=32),
        ),
    ]
