# Generated by Django 4.2.30 on 2026-08-09 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0082_remove_orderitem_custom_fields_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_fields_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='اطلاعات فیلدهای دلخواه'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='g4a4_order_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='شناسه سفارش G4A4'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='g4a4_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='وضعیت سفارش G4A4'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='g4a4_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.g4a4variation', verbose_name='واریانت G4A4'),
        ),
    ]
