# Generated by Django 4.2.30 on 2026-08-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0083_orderitem_custom_fields_data_orderitem_g4a4_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='jinx_image',
            field=models.CharField(blank=True, default='', help_text='آدرس تصویر سفارشی جینکس', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='jinx_text',
            field=models.TextField(blank=True, default='', help_text='متن دیالوگ سفارشی جینکس'),
        ),
        migrations.AddField(
            model_name='product',
            name='page_customization',
            field=models.JSONField(blank=True, default=dict, help_text='تنظیمات سفارشی\u200cسازی صفحه محصول'),
        ),
    ]
