# Generated by Django 4.2.30 on 2026-08-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0085_userprofile_national_card_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FORTNITE', 'فورتنایت'), ('PUBG', 'پابجی'), ('COD_MOBILE', 'کالاف دیوتی'), ('CLASH_ROYALE', 'کلش رویال'), ('CLASH_OF_CLANS', 'کلش اف کلنز'), ('BRAWL_STARS', 'براول استارز'), ('FREE_FIRE', 'فری فایر'), ('VALORANT', 'ولورانت'), ('RAINBOW_SIX', 'رینبو سیکس'), ('MARVEL_RIVALS', 'مارول ریوالز'), ('PING_REDUCTION', 'سرویس کاهش پینگ'), ('MOBILE_GAMES', 'بازی\u200cهای موبایل'), ('ROCKET_LEAGUE', 'راکت لیگ'), ('AI', 'هوش مصنوعی'), ('GIFTCARDS', 'گیفت کارت\u200cها'), ('GAMES', 'بازی\u200cها'), ('SUBSCRIPTIONS', 'اشتراک\u200cها'), ('ACCOUNTS', 'اکانت\u200cها'), ('BATTLENET', 'بتل\u200cنت'), ('INGAME', 'درون برنامه\u200cای')], default='FORTNITE', max_length=32),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(choices=[('FORTNITE', 'فورتنایت'), ('PUBG', 'پابجی'), ('COD_MOBILE', 'کالاف دیوتی'), ('CLASH_ROYALE', 'کلش رویال'), ('CLASH_OF_CLANS', 'کلش اف کلنز'), ('BRAWL_STARS', 'براول استارز'), ('FREE_FIRE', 'فری فایر'), ('VALORANT', 'ولورانت'), ('RAINBOW_SIX', 'رینبو سیکس'), ('MARVEL_RIVALS', 'مارول ریوالز'), ('PING_REDUCTION', 'سرویس کاهش پینگ'), ('MOBILE_GAMES', 'بازی\u200cهای موبایل'), ('ROCKET_LEAGUE', 'راکت لیگ'), ('AI', 'هوش مصنوعی'), ('GIFTCARDS', 'گیفت کارت\u200cها'), ('GAMES', 'بازی\u200cها'), ('SUBSCRIPTIONS', 'اشتراک\u200cها'), ('ACCOUNTS', 'اکانت\u200cها'), ('BATTLENET', 'بتل\u200cنت'), ('INGAME', 'درون برنامه\u200cای')], help_text='دسته\u200cبندی والد', max_length=32),
        ),
    ]
