# Generated by Django 4.2.30 on 2026-09-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0086_alter_product_category_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_16_9',
            field=models.CharField(blank=True, help_text='کاور 16:9 محصول (تصویر بزرگ در صفحه محصول)', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, help_text='آدرس کاور مربعی یا پیش\u200cفرض', max_length=500),
        ),
    ]
