var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/faq/privacy/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1smbgsi._.js")
R.c("server/chunks/ssr/app_faq_data_jsx_1ifobm8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0ybg_sq.js")
R.c("server/chunks/ssr/_0etmx64._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0um8i3u._.js")
R.c("server/chunks/ssr/node_modules_next_dist_05qu9g0._.js")
R.c("server/chunks/ssr/_04j38nu._.js")
R.c("server/chunks/ssr/_1cebomd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_faq_privacy_page_actions_20xu8m-.js")
R.m(30828)
module.exports=R.m(30828).exports
