from django.urls import path
from . import views
from . import views_categories
from . import reseller_views
from . import spin_views
from . import blog_views
from .chat_views import chat_user_api, chat_admin_api, chat_upload_api
from .ai_playground import ai_playground_api
from . import marketplace_views
from .kavenegar_admin_views import (
    kavenegar_admin_usage,
    external_zarinpal_topup_request,
    external_zarinpal_topup_callback,
    kavenegar_admin_manual_record,
)

urlpatterns = [
    path('products', views.products_list),
    path('products/<str:slug>', views.product_detail),
    path('products/<str:slug>/viewers', views.product_viewers),
    path('products/<str:slug>/comments', views.product_comments),
    path('products/fortnite-crew-pack/capacity', views.crewpack_capacity),
    path('comments/<int:comment_id>/reply', views.reply_comment),
    path('comments/<int:comment_id>', views.delete_comment),
    path('categories', views_categories.categories_list),
    path('categories/<str:category_code>', views_categories.category_products),
    path('categories/<str:category_code>/subcategories', views_categories.category_subcategories),
    path('orders', views.create_order),
    path('orders/<str:tracking>', views.order_status),
    path('ipinfo', views.ipinfo_lookup),
    path('auth/signup', views.signup),
    path('auth/login', views.login_view),
    path('auth/logout', views.logout_view),
    path('auth/me', views.me),
    path('user/exchange-points', views.exchange_points),
    path('auth/send-otp', views.send_otp_view),
    path('auth/verify-otp', views.verify_otp_view),
    path('auth/reset-password/request', views.reset_password_request),
    path('auth/reset-password/confirm', views.reset_password_confirm),
    path('me/orders', views.my_orders),
    path('me/orders/<str:tracking>/cancel', views.cancel_order),
    path('me/orders/<str:tracking>/update-info', views.user_update_order_info),
    # Live Chat URLs
    path('chat', chat_user_api),
    path('chat/upload', chat_upload_api),
    path('admin/chat', chat_admin_api),
    path('admin/ai-playground', ai_playground_api),
    path('admin/orders', views.admin_orders),
    path('admin/orders/previous', views.admin_previous_orders),
    path('admin/orders/refunded', views.admin_refunded_orders),
    path('admin/orders/canceled', views.admin_canceled_orders),
    path('admin/orders/<str:tracking>/status', views.admin_update_order_status),
    path('admin/orders/<str:tracking>/direct-chat', views.admin_send_direct_chat),
    path('admin/orders/<str:tracking>/emergency-ticket', views.admin_create_emergency_ticket),
    path('admin/orders/<str:tracking>/ai-verify-info', views.admin_verify_ai_info),
    path('admin/orders/<str:tracking>/unpin', views.admin_unpin_order),
    path('admin/orders/<str:tracking>/delete', views.admin_delete_order),
    path('admin/order-accounts/<int:account_id>/status', views.admin_update_account_status),
    path('admin/orders/<str:tracking>/refund-notify', views.admin_refund_notify),
    path('admin/orders/custom-dollar', views.admin_create_custom_dollar_order),
    path('admin/notifications', views.admin_notifications),
    path('admin/kavenegar/health', views.admin_kavenegar_health),
    path('admin/kavenegar/usage', kavenegar_admin_usage),
    path('admin/kavenegar/usage/', kavenegar_admin_usage),
    path('admin/kavenegar/topup/request', external_zarinpal_topup_request),
    path('admin/kavenegar/topup/request/', external_zarinpal_topup_request),
    path('admin/kavenegar/topup/callback', external_zarinpal_topup_callback),
    path('admin/kavenegar/topup/callback/', external_zarinpal_topup_callback),
    path('admin/kavenegar/topup/manual-record', kavenegar_admin_manual_record),
    path('admin/kavenegar/topup/manual-record/', kavenegar_admin_manual_record),
    path('admin/settings', views.admin_settings),
    path('admin/products', views.admin_products),
    path('admin/products/reorder', views.admin_products_reorder),
    path('admin/products/ai-fill', views.admin_product_ai_fill),
    path('admin/products/<int:product_id>/cover', views.admin_product_cover),
    path('admin/products/<int:product_id>/cover-16-9', views.admin_product_cover_16_9),
    path('admin/products/<int:product_id>', views.admin_product_detail),
    path('admin/subcategories', views.admin_subcategories),
    path('admin/subcategories/<int:pk>', views.admin_subcategory_detail),
    path('admin/users', views.admin_users),
    path('admin/users/<int:user_id>/delete', views.admin_user_delete),
    path('admin/discounts', views.admin_discounts),
    path('admin/discounts/<str:code>', views.admin_discount_detail),
    path('admin-cache-bust', views.admin_cache_bust),
    path('admin/xbox-accounts', views.admin_xbox_accounts),
    path('admin/xbox-accounts/<int:account_id>', views.admin_xbox_account_detail),
    path('admin/accounting', views.admin_accounting),
    path('admin/accounting/daily-lira-purchase', views.admin_daily_lira_purchase),
    path('admin/accounting/financial-config', views.admin_financial_config),
    path('admin/accounting/close-week', views.admin_close_financial_week),
    path('admin/accounting/transactions', views.admin_accounting_transactions),
    path('admin/accounting/transactions/<int:txn_id>', views.admin_accounting_transaction_detail),
    path('admin/accounting/settlements', views.admin_settlement_history),
    path('admin/accounting/settlements/<int:batch_id>', views.admin_delete_settlement_batch),
    path('admin/orders/<str:tracking>/settle', views.admin_settle_order),
    path('admin/orders/settle-bulk', views.admin_settle_bulk),
    path('admin/orders/unit-settle', views.admin_unit_settle),
    path('admin/accounting/oldest-unsettled', views.admin_oldest_unsettled),
    path('discounts/validate', views.discount_validate),
    # Blog / Articles
    path('blog/articles', blog_views.article_list),
    path('blog/articles/<slug:slug>', blog_views.article_detail),
    path('blog/categories', blog_views.category_list),
    path('admin/blog/articles', blog_views.admin_article_list),
    path('admin/blog/articles/<int:pk>', blog_views.admin_article_detail),
    path('admin/blog/categories', blog_views.admin_category_list),
    path('admin/blog/seo-generate', blog_views.admin_seo_generate),
    path('spin/status', spin_views.spin_status),
    path('spin', spin_views.spin),
    path('spin/recent-winners', spin_views.spin_recent_winners),
    path('me/referral', views.my_referral),
    path('me/referral/acknowledge', views.acknowledge_referrals),
    path('me/notifications', views.my_notifications),
    path('me/notifications/read', views.my_notifications),
    path('admin/site-notifications', views.admin_site_notifications),
    path('me/redeem/crewpack', views.redeem_crewpack),
    path('stats', views.public_stats),
    path('testimonials', views.public_testimonials),
    path('currency-rates', views.currency_rates),
    path('coins/games', views.coins_games_list),
    path('coins/<str:game_slug>', views.coins_game_detail),
    path('settings/public', views.public_settings),
    path('gta6/config', views.gta6_config),
    path('me/profile', views.update_profile),
    path('me/avatar', views.upload_avatar),
    path('me/wallet', views.wallet_details),
    path('me/wallet/topup', views.wallet_topup),
    path('me/wishlist', views.wishlist_list),
    path('me/wishlist/toggle', views.wishlist_toggle),
    path('payment/request/<str:tracking>', views.payment_request),
    path('payment/verify/<str:tracking>', views.payment_verify),
    path('payment/inquiry/<str:tracking>', views.payment_inquiry),
    path('discord/webhook/messages', views.discord_webhook_message),
    path('discord/webhook/priority', views.discord_webhook_priority),
    path('discord/bot/outbox', views.discord_bot_outbox),
    path('discord/bot/outbox/ack', views.discord_bot_outbox_ack),
    path('discord/channels', views.discord_admin_channels),
    path('discord/channels/<int:channel_id>/messages', views.discord_admin_messages),
    path('discord/channels/<int:channel_id>/send', views.discord_admin_send),

    # ---- Product Request endpoints ----
    path('product-requests', views.create_product_request),
    path('admin/product-requests', views.admin_product_requests),

    # ---- Reseller (همکار) endpoints ----
    path('reseller/signup', reseller_views.reseller_signup),
    path('reseller/auth/token', reseller_views.reseller_auth_token),
    path('reseller/logout', reseller_views.reseller_logout),
    path('reseller/me', reseller_views.reseller_me),
    path('reseller/welcome/ack', reseller_views.reseller_welcome_ack),
    path('reseller/profile', reseller_views.reseller_profile_update),
    path('reseller/phone-verify', reseller_views.reseller_phone_verify),
    path('reseller/catalog', reseller_views.reseller_catalog),
    path('reseller/orders', reseller_views.reseller_orders),
    path('reseller/orders/checkout', reseller_views.reseller_order_checkout),
    path('reseller/orders/verify', reseller_views.reseller_order_verify),
    path('reseller/orders/<str:tracking>', reseller_views.reseller_order_detail),
    path('reseller/orders/<str:tracking>/lira-diff', reseller_views.reseller_order_diff),
    path('reseller/orders/<str:tracking>/fill-accounts', reseller_views.reseller_order_fill_accounts),
    path('reseller/orders/<str:tracking>/return-unit', reseller_views.reseller_order_return_unit),
    path('reseller/wallet', reseller_views.reseller_wallet),
    path('reseller/stats', reseller_views.reseller_stats),
    path('reseller/referrals', reseller_views.reseller_referrals),
    path('reseller/wallet/topup', reseller_views.reseller_wallet_topup),
    path('reseller/wallet/verify', reseller_views.reseller_wallet_verify),
    path('reseller/channel-verify', reseller_views.reseller_channel_verify),

    # ---- Admin reseller management ----
    path('admin/resellers', reseller_views.admin_resellers),
    path('admin/resellers/create', reseller_views.admin_reseller_create),
    path('admin/resellers/<int:reseller_id>', reseller_views.admin_reseller_update),
    path('admin/resellers/<int:reseller_id>/details', reseller_views.admin_reseller_details),
    path('admin/resellers/<int:reseller_id>/rotate-token', reseller_views.admin_reseller_rotate_token),
    path('admin/resellers/<int:reseller_id>/wallet-adjust', reseller_views.admin_reseller_wallet_adjust),
    path('admin/resellers/<int:reseller_id>/channel-check', reseller_views.admin_reseller_channel_check),
    path('admin/reseller-tiers', reseller_views.admin_reseller_tiers),
    path('admin/reseller-tiers/upsert', reseller_views.admin_reseller_tiers_upsert),
    path('admin/reseller-tiers/clear-override', reseller_views.admin_reseller_tiers_clear_override),
    path('admin/reseller-tiers/overrides-summary', reseller_views.admin_reseller_price_overrides_summary),
    path('admin/reseller-pricing-tour/ack', views.admin_reseller_pricing_tour_ack),

    # ---- Abandoned cart (سبدهای رها‌شده) ----
    path('cart/sync', views.cart_sync),
    path('cart/validate', views.cart_validate),
    path('performance/vitals', views.performance_vitals),
    path('admin/abandoned-carts', views.admin_abandoned_carts),
    path('admin/abandoned-carts/<int:cart_id>/remind', views.admin_abandoned_cart_remind),
    path('admin/abandoned-carts/<int:cart_id>/delete', views.admin_abandoned_cart_delete),

    # ---- Marketplace (بازارچه اکانت) ----
    path('market/listings', marketplace_views.get_listings),
    path('market/listings/mine', marketplace_views.get_my_listings),
    path('market/listings/create', marketplace_views.create_listing),
    path('market/listings/<int:listing_id>', marketplace_views.get_listing_detail),
    path('market/listings/<int:listing_id>/images', marketplace_views.upload_listing_image),
    path('market/listings/<int:listing_id>/favorite', marketplace_views.toggle_favorite),
    path('market/listings/<int:listing_id>/report', marketplace_views.report_listing),
    
    path('market/deals', marketplace_views.initiate_deal),
    path('market/deals/mine', marketplace_views.get_my_deals),
    path('market/deals/<int:deal_id>/credentials', marketplace_views.submit_credentials),
    path('market/deals/<int:deal_id>/confirm', marketplace_views.confirm_deal),
    path('market/deals/<int:deal_id>/dispute', marketplace_views.dispute_deal),
    
    path('market/seller/dashboard', marketplace_views.get_seller_dashboard),
    path('market/seller/dashboard/payout-info', marketplace_views.update_seller_payment_info),
    
    path('admin/market/review-queue', marketplace_views.admin_review_queue),
    path('admin/market/listings', marketplace_views.admin_all_listings),
    path('admin/market/listings/<int:listing_id>/approve', marketplace_views.admin_approve_listing),
    path('admin/market/listings/<int:listing_id>/reject', marketplace_views.admin_reject_listing),
    path('admin/market/listings/<int:listing_id>/update', marketplace_views.admin_update_listing),
    path('admin/market/listings/<int:listing_id>/images', marketplace_views.admin_upload_listing_image),
    path('admin/market/images/<int:image_id>/delete', marketplace_views.admin_delete_listing_image),
    path('admin/market/listings/<int:listing_id>/delete', marketplace_views.admin_delete_listing),
    path('admin/market/deals', marketplace_views.admin_all_deals),
    path('admin/market/deals/<int:deal_id>/update', marketplace_views.admin_update_deal),
    path('admin/market/deals/<int:deal_id>/delete', marketplace_views.admin_delete_deal),

    # ---- Identity Verification (احراز هویت) ----
    path('me/verify-identity', views.verify_identity),
    path('admin/users/verifications', views.admin_verification_list),
    path('admin/users/verifications/<int:profile_id>/approve', views.admin_approve_verification),
    path('admin/users/verifications/<int:profile_id>/reject', views.admin_reject_verification),
]
