var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/panel/admin/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1xcivpr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1trbk1g.js")
R.c("server/chunks/ssr/[root-of-the-server]__0um8i3u._.js")
R.c("server/chunks/ssr/node_modules_next_dist_05qu9g0._.js")
R.c("server/chunks/ssr/_04j38nu._.js")
R.c("server/chunks/ssr/_1cebomd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/app_panel_layout_jsx_1eepigi._.js")
R.c("server/chunks/ssr/app_panel_admin_layout_jsx_1ikp0_i._.js")
R.c("server/chunks/ssr/_next-internal_server_app_panel_admin_page_actions_1a3toip.js")
R.m(21600)
module.exports=R.m(21600).exports
