export const placeholderFeatured = [
  {
    id: 1,
    slug: "fortnite-crew-pack",
    name_fa: "کروپک فورتنایت",
    subtitle: "Crew Pack | تحویل سریع",
    category: "fortnite",
    category_title: "فورتنایت",
    image_url: "/products/crewpack.webp",
    image_base: "/products/crewpack",
    price_from: true,
  },
  {
    id: 2,
    slug: "fortnite-freediver",
    name_fa: "فری‌دایور فورتنایت",
    subtitle: "Free Diver Bundle",
    category: "fortnite",
    category_title: "فورتنایت",
    image_url: "/products/freediver.webp",
    image_base: "/products/freediver",
    price_from: false,
  },
  {
    id: 4,
    slug: "fortnite-starter-pack",
    name_fa: "استارتر پک فورتنایت",
    subtitle: "Starter Pack",
    category: "fortnite",
    category_title: "فورتنایت",
    image_url: "/products/starterpack.webp",
    image_base: "/products/starterpack",
    price_from: true,
  },
  {
    id: 3,
    slug: "v-bucks",
    name_fa: "وی‌باکس فورتنایت",
    subtitle: "V-Bucks",
    category: "fortnite",
    category_title: "فورتنایت",
    image_url: "/products/product_vbucks.webp",
    image_base: "/products/product_vbucks",
    price_from: true,
  },
  {
    id: 6,
    slug: "fortnite-battle-pass",
    name_fa: "بتل پس فورتنایت",
    subtitle: "Battle Pass",
    category: "fortnite",
    category_title: "فورتنایت",
    image_url: "/products/battlepass.webp",
    image_base: "/products/battlepass",
    price_from: false,
  },
  {
    id: 5,
    slug: "fortnite-save-the-world",
    name_fa: "سیو د ورلد فورتنایت",
    subtitle: "Save the World",
    category: "fortnite",
    category_title: "فورتنایت",
    image_url: "/products/savetheworld.webp",
    image_base: "/products/savetheworld",
    price_from: false,
  },
  {
    id: 7,
    slug: "fortnite-glided-elite-pack",
    name_fa: "پک Glided Elite",
    subtitle: "Glided Elite Pack",
    category: "fortnite",
    category_title: "فورتنایت",
    image_url: "/products/pack_glided_elites.webp",
    image_base: "/products/pack_glided_elites",
    price_from: false,
  },
  {
    id: 8,
    slug: "spotify-subscription",
    name_fa: "اشتراک اسپاتیفای",
    subtitle: "Spotify Premium",
    category: "subscriptions",
    category_title: "اشتراک‌ها",
    image_url: "/products/spotify.webp",
    image_base: "/products/spotify",
    price_from: true,
  },
  {
    id: 9,
    slug: "chatgpt-subscription",
    name_fa: "اشتراک ChatGPT",
    subtitle: "ChatGPT Plus",
    category: "ai",
    category_title: "هوش مصنوعی",
    image_url: "/products/chatgpt.webp",
    image_base: "/products/chatgpt",
    price_from: true,
  },
  {
    id: 10,
    slug: "gemini-subscription",
    name_fa: "اشتراک Gemini",
    subtitle: "Gemini Advanced",
    category: "ai",
    category_title: "هوش مصنوعی",
    image_url: "/products/gemini.webp",
    image_base: "/products/gemini",
    price_from: true,
  },
  {
    id: 11,
    slug: "steam-giftcard",
    name_fa: "گیفت کارت استیم",
    subtitle: "Steam Gift Card | تحویل فوری",
    category: "giftcards",
    category_title: "گیفت کارت‌ها",
    sub: "steam",
    image_url: "/images/games/steam.webp",
    image_base: "/images/games/steam",
    price_from: true,
  },
  {
    id: 12,
    slug: "playstation-giftcard",
    name_fa: "گیفت کارت پلی استیشن",
    subtitle: "PSN Gift Card | تحویل فوری",
    category: "giftcards",
    category_title: "گیفت کارت‌ها",
    sub: "ps",
    image_url: "/images/games/psn.webp",
    image_base: "/images/games/psn",
    price_from: true,
  },
  {
    id: 13,
    slug: "xbox-giftcard",
    name_fa: "گیفت کارت ایکس باکس",
    subtitle: "Xbox Gift Card | تحویل فوری",
    category: "giftcards",
    category_title: "گیفت کارت‌ها",
    sub: "xbox",
    image_url: "/images/games/xbox.webp",
    image_base: "/images/games/xbox",
    price_from: true,
  },
  {
    id: 14,
    slug: "gta6",
    name_fa: "بازی GTA VI",
    subtitle: "Grand Theft Auto VI",
    category: "games",
    category_title: "بازی‌ها",
    image_url: "/products/gta6/ps5-standard.webp",
    image_base: "/products/gta6/ps5-standard",
    price_from: true,
  },
];

